# Generated by Django 4.2.4 on 2023-11-05 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_name', models.CharField(blank=True, db_column='StationName', max_length=50, null=True)),
                ('c_year', models.IntegerField(blank=True, db_column='CYear', null=True)),
                ('c_month', models.IntegerField(blank=True, db_column='CMonth', null=True)),
                ('c_day', models.IntegerField(blank=True, db_column='CDay', null=True)),
                ('c_date', models.DateField(blank=True, db_column='CDate', null=True)),
                ('value', models.DecimalField(blank=True, db_column='Value', decimal_places=6, max_digits=15, null=True)),
                ('data_type', models.CharField(blank=True, db_column='DataType', max_length=50, null=True)),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WeatherDataNew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station', models.CharField(blank=True, db_column='Station', max_length=50, null=True)),
                ('c_year', models.IntegerField(blank=True, db_column='CYear', null=True)),
                ('c_month', models.IntegerField(blank=True, db_column='CMonth', null=True)),
                ('c_day', models.IntegerField(blank=True, db_column='CDay', null=True)),
                ('c_date', models.DateField(blank=True, db_column='CDate', null=True)),
                ('value', models.DecimalField(blank=True, db_column='Value', decimal_places=6, max_digits=15, null=True)),
                ('data_type', models.CharField(blank=True, db_column='datatype', max_length=50, null=True)),
                ('source', models.CharField(blank=True, db_column='source', max_length=50, null=True)),
            ],
            options={
                'managed': False,
            },
        ),
    ]
