# Generated by Django 4.2.4 on 2023-11-05 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('temperature_map', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='weatherdata',
            table='WeatherData',
        ),
        migrations.AlterModelTable(
            name='weatherdatanew',
            table='WeatherDataNew',
        ),
    ]
