# Generated by Django 4.2.4 on 2024-01-10 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temperature_map', '0003_weatherdataprediction'),
    ]

    operations = [
        migrations.CreateModel(
            name='PointsPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, db_column='Station', max_length=50, null=True)),
                ('place_id', models.CharField(blank=True, db_column='place id', max_length=50, null=True)),
                ('lat', models.DecimalField(blank=True, db_column='lat', decimal_places=6, max_digits=18, null=True)),
                ('lon', models.DecimalField(blank=True, db_column='lon', decimal_places=6, max_digits=18, null=True)),
            ],
            options={
                'db_table': 'points_place',
                'managed': False,
            },
        ),
    ]
