# Generated by Django 4.2.4 on 2024-01-22 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temperature_map', '0005_weatherdatameteosource'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weatherdatameteosource',
            name='astro_moon_rise',
            field=models.DateTimeField(blank=True, db_column='astro_moon_rise', null=True),
        ),
        migrations.AlterField(
            model_name='weatherdatameteosource',
            name='astro_moon_set',
            field=models.DateTimeField(blank=True, db_column='astro_moon_set', null=True),
        ),
        migrations.AlterField(
            model_name='weatherdatameteosource',
            name='astro_sun_rise',
            field=models.DateTimeField(blank=True, db_column='astro_sun_rise', null=True),
        ),
        migrations.AlterField(
            model_name='weatherdatameteosource',
            name='astro_sun_set',
            field=models.DateTimeField(blank=True, db_column='astro_sun_set', null=True),
        ),
    ]
